[versions]
kotlin = "2.1.10"
shadow = "9.0.0-SNAPSHOT"
run-task = "2.3.1"

jgit = "7.1.0.202411261347-r"
paper-api = "1.21.4-R0.1-SNAPSHOT"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }

[libraries]
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }